export const POPULAR_CAMERA_BRANDS = [
  'Canon',
  'Nikon',
  'Sony',
  'Olympus',
  'OM System',
  'Fujifilm',
  'Panasonic',
  'Lumix',
  'Kodak',
  'Minolta',
  'Konica Minolta',
  'Pentax',
  'Ricoh',
  'Leica',
  'Polaroid',
  'Casio',
  'Samsung',
  'GoPro',
  'DJI',
  'Insta360'
];

export const MORE_CAMERA_BRANDS = [
  'Yashica',
  'Contax',
  'Zeiss Ikon',
  'Carl Zeiss',
  'Voigtlander',
  'Mamiya',
  'Hasselblad',
  'Rolleiflex',
  'Rollei',
  'Bronica',
  'Minox',
  'Agfa',
  'Argus',
  'Ansco',
  'Bell & Howell',
  'Chinon',
  'Miranda',
  'Topcon',
  'Praktica',
  'Exakta',
  'Kiev',
  'Zorki',
  'FED',
  'Zenit',
  'Lomo',
  'Lomography',
  'Holga',
  'Diana',
  'Graflex',
  'Linhof',
  'Sinar',
  'Toyo',
  'Wista',
  'Horseman',
  'Sigma',
  'Tamron',
  'Tokina',
  'Samyang',
  'Rokinon',
  'Vivitar',
  'Soligor',
  'Schneider-Kreuznach',
  'Rodenstock',
  'Meyer-Optik',
  'Helios',
  'Jupiter',
  'Industar',
  'Epson',
  'HP',
  'Canon Printer',
  'Nikon Scanner',
  'Plustek',
  'Wolverine',
  'Elgato',
  'Blackmagic Design',
  'JVC',
  'Sony Handycam',
  'Panasonic Camcorder',
  'Canon Vixia',
  'Sharp',
  'Toshiba',
  'Sanyo'
];

export const CAMERA_BRANDS = [...POPULAR_CAMERA_BRANDS, ...MORE_CAMERA_BRANDS, 'Other / Unlisted Brand'];

export const TOP_LEVEL_CATEGORIES = [
  { slug: 'digital-cameras', label: 'Digital Cameras' },
  { slug: 'vintage-digital-cameras', label: 'Vintage Digital Cameras' },
  { slug: 'film-cameras', label: 'Film Cameras' },
  { slug: 'point-and-shoot-cameras', label: 'Point & Shoot Cameras' },
  { slug: 'compact-digital-cameras', label: 'Compact Digital Cameras' },
  { slug: 'dslr-cameras', label: 'DSLR Cameras' },
  { slug: 'mirrorless-cameras', label: 'Mirrorless Cameras' },
  { slug: 'rangefinder-cameras', label: 'Rangefinder Cameras' },
  { slug: 'medium-format-cameras', label: 'Medium Format Cameras' },
  { slug: 'instant-cameras', label: 'Instant Cameras' },
  { slug: 'bridge-cameras', label: 'Bridge Cameras' },
  { slug: 'camcorders', label: 'Camcorders' },
  { slug: 'action-cameras', label: 'Action Cameras' },
  { slug: 'lenses', label: 'Lenses' },
  { slug: 'camera-accessories', label: 'Camera Accessories' },
  { slug: 'batteries-chargers', label: 'Batteries & Chargers' },
  { slug: 'memory-cards-storage', label: 'Memory Cards & Storage' },
  { slug: 'flashes-lighting', label: 'Flashes & Lighting' },
  { slug: 'tripods-supports', label: 'Tripods & Supports' },
  { slug: 'camera-bags-cases', label: 'Camera Bags & Cases' },
  { slug: 'straps-grips', label: 'Straps & Grips' },
  { slug: 'filters', label: 'Filters' },
  { slug: 'lens-caps-hoods', label: 'Lens Caps & Hoods' },
  { slug: 'adapters-mounts', label: 'Adapters & Mounts' },
  { slug: 'film-darkroom', label: 'Film & Darkroom' },
  { slug: 'scanners-printers', label: 'Scanners & Printers' },
  { slug: 'printers', label: 'Printers' },
  { slug: 'electronics', label: 'Electronics' },
  { slug: 'video-games', label: 'Video Games' },
  { slug: 'trading-cards-collectibles', label: 'Trading Cards & Collectibles' },
  { slug: 'manuals-paperwork', label: 'Manuals & Paperwork' },
  { slug: 'parts-repair', label: 'Parts & Repair' },
  { slug: 'collectible-cameras', label: 'Collectible Cameras' },
  { slug: 'bundles-kits', label: 'Bundles & Kits' }
];

export const PRODUCT_TYPES = [
  'CCD Digital Cameras',
  'Canon PowerShot',
  'Nikon Coolpix',
  'Sony Cyber-shot',
  'Olympus Digital Cameras',
  'Kodak EasyShare',
  'Fujifilm FinePix',
  'Panasonic Lumix',
  'Casio Exilim',
  'Compact Point & Shoot',
  'Waterproof / Tough Cameras',
  'Superzoom / Bridge Cameras',
  '35mm Film Cameras',
  '120 / Medium Format Cameras',
  'Large Format Cameras',
  'Instant Film Cameras',
  'Disposable Cameras',
  'Rangefinders',
  'SLR Film Cameras',
  'TLR Cameras',
  'Box Cameras',
  'Folding Cameras',
  'Toy Cameras',
  'Canon EF',
  'Canon EF-S',
  'Canon RF',
  'Nikon F',
  'Nikon Z',
  'Sony E',
  'Sony A',
  'Micro Four Thirds',
  'Fujifilm X',
  'Pentax K',
  'Leica M',
  'Leica R',
  'Minolta SR / MD / MC',
  'M42 Screw Mount',
  'Medium Format Lenses',
  'Vintage Manual Focus Lenses',
  'Lens Adapters',
  'Battery Chargers',
  'Batteries',
  'Memory Cards',
  'SD Cards',
  'CF Cards',
  'xD Picture Cards',
  'Memory Stick',
  'Camera Cases',
  'Camera Bags',
  'Neck Straps',
  'Wrist Straps',
  'Lens Filters',
  'Lens Caps',
  'Lens Hoods',
  'Tripods',
  'Monopods',
  'Flashes',
  'Cables',
  'USB Cables',
  'AV Cables',
  'Remote Shutters',
  'Cleaning Kits',
  'Manuals',
  'Original Boxes',
  'Parts/Repair Components'
];

export const FUNCTIONAL_STATUSES = [
  'Tested',
  'Ready to Shoot',
  'Powers On',
  'Fully Functional',
  'Minor Issue',
  'Needs Repair',
  'Untested',
  'Parts Only'
];

export const LENS_MOUNTS = [
  'Canon EF',
  'Canon EF-S',
  'Canon RF',
  'Nikon F',
  'Nikon Z',
  'Sony E',
  'Sony A',
  'Micro Four Thirds',
  'Fujifilm X',
  'Pentax K',
  'Leica M',
  'Leica R',
  'Minolta SR / MD / MC',
  'M42 Screw Mount',
  'Medium Format',
  'Other / Unknown'
];

export const FILM_FORMATS = ['35mm', '120', '220', '110', '126', 'Instant', 'Large Format', 'APS'];

export const STORAGE_TYPES = [
  'SD Card',
  'microSD',
  'CompactFlash',
  'xD Picture Card',
  'Memory Stick',
  'Internal Memory',
  'MiniDV',
  'VHS-C',
  'Hi8 / Digital8'
];

export const INCLUDE_FILTER_OPTIONS = [
  { value: 'battery', label: 'Includes battery' },
  { value: 'charger', label: 'Includes charger' },
  { value: 'memory-card', label: 'Includes memory card' },
  { value: 'strap', label: 'Includes strap' },
  { value: 'case', label: 'Includes case' },
  { value: 'manual', label: 'Includes manual' },
  { value: 'original-box', label: 'Includes original box' },
  { value: 'sample-photos', label: 'Has sample photos' },
  { value: 'actual-photos', label: 'Actual photos shown' },
  { value: 'tested', label: 'Shutterbug tested' },
  { value: 'parts-repair', label: 'Parts / repair' }
];
