import { randomBytes } from 'node:crypto';

export type TradeInItemTypeValue = 'DIGITAL_CAMERA'|'FILM_CAMERA'|'LENS'|'ACCESSORY'|'COLLECTION'|'OTHER';
export type TradeInConditionValue = 'LIKE_NEW'|'EXCELLENT'|'GOOD'|'FAIR'|'POOR'|'FOR_PARTS'|'UNKNOWN';
export type TradeInPayoutMethodValue = 'CASH'|'STORE_CREDIT';
export type TradeInStatusValue = 'DRAFT'|'SUBMITTED'|'UNDER_REVIEW'|'OFFER_SENT'|'OFFER_ACCEPTED'|'OFFER_DECLINED'|'SHIPPING_ARRANGED'|'RECEIVED'|'INSPECTING'|'REVISED_OFFER_SENT'|'COMPLETED'|'CANCELLED';
export const tradeInItemLabels: Record<TradeInItemTypeValue, string> = {
  DIGITAL_CAMERA:'Digital camera',FILM_CAMERA:'Film camera',LENS:'Lens',ACCESSORY:'Accessory',COLLECTION:'Camera collection',OTHER:'Other gear'
};
export const tradeInConditionLabels: Record<TradeInConditionValue,string>={LIKE_NEW:'Like new',EXCELLENT:'Excellent',GOOD:'Good',FAIR:'Fair',POOR:'Poor',FOR_PARTS:'For parts or repair',UNKNOWN:'Not sure'};
export const tradeInStatusLabels:Record<TradeInStatusValue,string>={DRAFT:'Draft',SUBMITTED:'Submitted',UNDER_REVIEW:'Under review',OFFER_SENT:'Offer ready',OFFER_ACCEPTED:'Offer accepted',OFFER_DECLINED:'Offer declined',SHIPPING_ARRANGED:'Shipping arranged',RECEIVED:'Gear received',INSPECTING:'Inspection in progress',REVISED_OFFER_SENT:'Revised offer ready',COMPLETED:'Completed',CANCELLED:'Cancelled'};
export const tradeInStatusSteps:TradeInStatusValue[]=['SUBMITTED','UNDER_REVIEW','OFFER_SENT','OFFER_ACCEPTED','SHIPPING_ARRANGED','RECEIVED','INSPECTING','COMPLETED'];
const itemTypes=new Set<unknown>(Object.keys(tradeInItemLabels));const conditions=new Set<unknown>(Object.keys(tradeInConditionLabels));const payouts=new Set<unknown>(['CASH','STORE_CREDIT']);
function text(value:unknown,max:number){return typeof value==='string'?value.trim().slice(0,max):'';}
export type TradeInDraftInput={itemType:TradeInItemTypeValue|null;brand:string;model:string;modelUnknown:boolean;quantity:number;condition:TradeInConditionValue|null;powersOn:boolean|null;functionalNotes:string;cosmeticNotes:string;includedItems:string[];additionalNotes:string;payoutPreference:TradeInPayoutMethodValue|null;phone:string;localHandoffRequested:boolean};
export function normalizeTradeInInput(value:unknown):TradeInDraftInput{const input=value&&typeof value==='object'?value as Record<string,unknown>:{};const quantity=Number(input.quantity);return{itemType:itemTypes.has(input.itemType)?input.itemType as TradeInItemTypeValue:null,brand:text(input.brand,100),model:text(input.model,160),modelUnknown:input.modelUnknown===true,quantity:Number.isInteger(quantity)?Math.min(50,Math.max(1,quantity)):1,condition:conditions.has(input.condition)?input.condition as TradeInConditionValue:null,powersOn:typeof input.powersOn==='boolean'?input.powersOn:null,functionalNotes:text(input.functionalNotes,2000),cosmeticNotes:text(input.cosmeticNotes,2000),includedItems:Array.isArray(input.includedItems)?[...new Set(input.includedItems.map(item=>text(item,80)).filter(Boolean))].slice(0,20):[],additionalNotes:text(input.additionalNotes,3000),payoutPreference:payouts.has(input.payoutPreference)?input.payoutPreference as TradeInPayoutMethodValue:null,phone:text(input.phone,40),localHandoffRequested:input.localHandoffRequested===true};}
export function tradeInSubmissionErrors(input:TradeInDraftInput,imageCount:number){const errors:string[]=[];if(!input.itemType)errors.push('Choose a gear type.');if(!input.brand)errors.push('Enter the brand.');if(!input.modelUnknown&&!input.model)errors.push('Enter the model or mark it unknown.');if(!input.condition)errors.push('Choose the closest condition.');if(!input.payoutPreference)errors.push('Choose cash or store credit.');if(imageCount<2)errors.push('Add at least two clear photos.');return errors;}
export function createTradeInReference(now=new Date(),entropy=randomBytes(4).toString('hex')){return `TI-${now.getUTCFullYear()}-${entropy.toUpperCase()}`;}
export function isCustomerEditableTradeIn(status:TradeInStatusValue){return status==='DRAFT';}
export function statusTone(status:TradeInStatusValue){if(status==='COMPLETED')return 'bg-mint text-forest';if(status==='CANCELLED'||status==='OFFER_DECLINED')return 'bg-sand text-ink';if(status==='OFFER_SENT'||status==='REVISED_OFFER_SENT')return 'bg-clay/20 text-ink';return 'bg-white text-moss';}