import { getPublicSiteUrl, sendTransactionalEmail } from '@/lib/email';
import { requirePrisma } from '@/lib/prisma';
import { site } from '@/lib/seo';
import { tradeInStatusLabels } from '@/lib/trade-ins';
function esc(value:string){return value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function shell(title:string,body:string,href:string,cta:string){return `<div style="font-family:Arial,sans-serif;line-height:1.6;color:#16231d;background:#fde9cd;padding:24px"><div style="max-width:620px;margin:0 auto;background:#fff;border:1px solid rgba(22,35,29,.12);border-radius:8px;padding:24px"><p style="font-size:12px;font-weight:700;letter-spacing:.18em;text-transform:uppercase;color:#2f6f4e">Shutterbug Camera Shop</p><h1 style="font-family:Georgia,serif">${esc(title)}</h1><p>${esc(body)}</p><p style="margin:24px 0"><a href="${esc(href)}" style="display:inline-block;background:#24543a;color:white;text-decoration:none;border-radius:999px;padding:12px 20px;font-weight:700">${esc(cta)}</a></p><p style="font-size:13px;color:rgba(22,35,29,.65)">Questions? Contact ${esc(site.supportEmail)}.</p></div></div>`;}
export async function notifyTradeInSubmitted(id:string){
 try{const item=await requirePrisma().tradeInSubmission.findUnique({where:{id},include:{customer:true}});if(!item)return;const customerUrl=`${getPublicSiteUrl()}/account/trade-ins/${item.id}`;const adminUrl=`${getPublicSiteUrl()}/admin/trade-ins/${item.id}`;await Promise.all([
  sendTransactionalEmail({to:item.customer.email,subject:`Trade-in ${item.reference} received`,text:`We received your trade-in submission ${item.reference}. We will review the details and photos before sending a preliminary offer. Track it at ${customerUrl}`,html:shell('We received your trade-in','We will review your details and private photos before sending a preliminary offer.',customerUrl,'View trade-in'),idempotencyKey:`trade-in-${item.id}-submitted-customer`}),
  sendTransactionalEmail({to:process.env.ADMIN_TRADE_IN_EMAIL||process.env.ADMIN_EMAIL||site.supportEmail,subject:`New trade-in ${item.reference}`,text:`A new trade-in was submitted by ${item.customer.email}. Review it at ${adminUrl}`,html:shell('New trade-in submitted',`${item.customer.email} submitted ${item.brand} ${item.model||'unknown model'}.`,adminUrl,'Review submission'),idempotencyKey:`trade-in-${item.id}-submitted-admin`})
 ]);}catch(error){console.error('[trade-in-email]',error instanceof Error?error.message:error);}
}
export async function notifyTradeInUpdate(id:string,message:string,eventKey:string){
 try{const item=await requirePrisma().tradeInSubmission.findUnique({where:{id},include:{customer:true}});if(!item)return;const url=`${getPublicSiteUrl()}/account/trade-ins/${item.id}`;await sendTransactionalEmail({to:item.customer.email,subject:`${tradeInStatusLabels[item.status]} · ${item.reference}`,text:`${message}\n\nView your trade-in: ${url}`,html:shell(tradeInStatusLabels[item.status],message,url,'View trade-in'),idempotencyKey:`trade-in-${item.id}-${eventKey}`});}catch(error){console.error('[trade-in-email]',error instanceof Error?error.message:error);}
}