'use client';
import Image from 'next/image';
import { useCart } from './CartProvider';
import { useBagPanel } from './BagPanel';

export function CartLink({compact=false}:{compact?:boolean}){
 const {count}=useCart();const {open,toggle}=useBagPanel();const displayCount=count>99?'99+':String(count);const ariaLabel=count?`Bag, ${count} item${count===1?'':'s'}`:'Bag';
 if(compact)return <button type="button" aria-label={open?'Close bag panel':ariaLabel} aria-expanded={open} aria-controls="header-bag-panel" onClick={event=>toggle(event.currentTarget)} className="relative flex h-11 w-11 shrink-0 items-center justify-center rounded-lg transition hover:bg-forest/5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-moss"><Image src="/shutterbug-bag-icon.png" alt="" width={32} height={32} sizes="2rem" className="h-8 w-8 rounded-md object-contain"/>{count?<span className="absolute right-0 top-0.5 flex h-4 min-w-4 items-center justify-center rounded-full bg-[#b8523b] px-1 text-[.6rem] font-semibold leading-none text-white">{displayCount}</span>:null}</button>;
 return <button type="button" aria-label={open?'Close bag panel':ariaLabel} aria-expanded={open} aria-controls="header-bag-panel" onClick={event=>toggle(event.currentTarget)} className="relative inline-flex h-14 w-14 shrink-0 items-center justify-center rounded-xl border border-ink/15 bg-[#faf4e8] shadow-sm transition hover:border-moss/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-moss"><span className="block h-full w-full overflow-hidden rounded-xl bg-[#faf4e8]"><Image src="/shutterbug-bag-icon.png" alt="" width={56} height={56} sizes="3.5rem" className="h-full w-full scale-[1.35] object-cover"/></span>{count?<span className="absolute -right-1 -top-1 flex h-5 min-w-5 items-center justify-center rounded-full bg-forest px-1.5 text-[0.65rem] font-bold leading-none text-white">{displayCount}</span>:null}</button>;
}