'use client';
import Image from 'next/image';
import Link from 'next/link';
import type { CartValidationItem } from '@/lib/cart-validation';
import { formatCents } from '@/lib/money';
import { useValidatedCart } from './useValidatedCart';
function placeholder(id:string,quantity:number):CartValidationItem{return{id,sku:'',slug:'',title:'Checking item…',image:'/shutterbug-product-placeholder.png',condition:'Checking current inventory',statusLabel:'Checking',requestedQuantity:quantity,validatedQuantity:0,availableQuantity:0,unitPriceCents:0,lineTotalCents:0,purchasable:false};}
export function CartPageClient({signedIn=false}:{signedIn?:boolean}){
 const {items,hydrated,validation,loading,error,hasBlockingIssue,updateQuantity,removeItem,clearCart}=useValidatedCart();
 if(!hydrated)return <div className="mt-10 rounded-[1.5rem] border border-ink/10 bg-white p-10 text-center shadow-sm"><p className="font-serif text-3xl font-bold text-ink">Loading your bag</p><p className="mt-3 text-ink/60">Checking the camera gear saved on this device.</p></div>;
 if(!items.length)return <Empty signedIn={signedIn}/>;
 const display=validation?.items.length?validation.items:items.map(item=>placeholder(item.id,item.quantity));const subtotal=validation?.subtotalCents??0;
 return <div className="mt-10 grid items-start gap-8 lg:grid-cols-[minmax(0,1fr)_23rem]">
  <section aria-label="Bag items" className="grid gap-5">{display.map(item=><article key={item.id} className="grid gap-5 rounded-[1.25rem] border border-ink/10 bg-white p-5 shadow-sm sm:grid-cols-[9rem_minmax(0,1fr)_auto]">
   <Image src={item.image} alt={item.title} width={180} height={180} sizes="9rem" unoptimized={item.image.startsWith('http')||item.image.endsWith('.svg')} className="aspect-square w-36 rounded-lg bg-sand object-contain"/>
   <div className="min-w-0">{item.slug?<Link href={`/shop/${item.slug}`} className="font-serif text-2xl font-bold text-ink hover:text-moss">{item.title}</Link>:<p className="font-serif text-2xl font-bold text-ink">{item.title}</p>}<p className="mt-2 text-sm text-ink/65"><span className="font-semibold text-ink">Condition:</span> {item.condition}</p><p className={`mt-2 text-sm font-semibold ${item.purchasable?'text-forest':'text-[#9b3d2e]'}`}>{item.statusLabel}</p>{item.issue?<p className="mt-3 rounded-lg bg-sand p-3 text-sm font-semibold text-ink">{item.issue}</p>:<p className="mt-3 text-sm text-ink/55">Availability checked against current inventory.</p>}
    <div className="mt-5 flex flex-wrap items-center gap-3"><div className="inline-flex items-center overflow-hidden rounded-full border border-ink/15 bg-cream"><button type="button" aria-label={`Decrease quantity for ${item.title}`} onClick={()=>updateQuantity(item.id,item.requestedQuantity-1)} disabled={item.requestedQuantity<=1} className="h-10 w-10 font-bold text-ink disabled:opacity-35">−</button><span className="min-w-9 text-center text-sm font-bold">{item.requestedQuantity}</span><button type="button" aria-label={`Increase quantity for ${item.title}`} onClick={()=>updateQuantity(item.id,item.requestedQuantity+1)} disabled={item.requestedQuantity>=Math.max(1,item.availableQuantity)} className="h-10 w-10 font-bold text-ink disabled:opacity-35">+</button></div>{item.validatedQuantity>0&&item.validatedQuantity!==item.requestedQuantity?<button type="button" onClick={()=>updateQuantity(item.id,item.validatedQuantity)} className="text-sm font-bold text-moss">Use available quantity ({item.validatedQuantity})</button>:null}<button type="button" onClick={()=>removeItem(item.id)} className="text-sm font-semibold text-ink/60 underline-offset-4 hover:text-ink hover:underline">Remove</button></div>
   </div><div className="sm:text-right"><p className="text-xl font-bold text-ink">{formatCents(item.lineTotalCents)}</p><p className="mt-1 text-xs text-ink/50">{formatCents(item.unitPriceCents)} each</p></div>
  </article>)}<button type="button" onClick={clearCart} className="justify-self-start text-sm font-semibold text-ink/55 underline-offset-4 hover:text-ink hover:underline">Clear bag</button></section>
  <aside className="rounded-[1.25rem] border border-ink/10 bg-white p-6 shadow-soft lg:sticky lg:top-44"><p className="text-sm font-bold uppercase tracking-[.18em] text-moss">Order summary</p><div className="mt-5 space-y-3 border-b border-ink/10 pb-5 text-sm"><p className="flex justify-between gap-4 text-ink/70"><span>Merchandise subtotal</span><strong className="text-ink">{loading?'Checking…':formatCents(subtotal)}</strong></p><p className="flex justify-between gap-4 text-ink/70"><span>Shipping</span><span>Calculated at checkout</span></p><p className="flex justify-between gap-4 text-ink/70"><span>Estimated tax</span><span>Calculated at checkout</span></p></div><p className="mt-5 flex items-baseline justify-between gap-4"><span className="font-serif text-xl font-bold text-ink">Subtotal</span><span className="font-serif text-3xl font-bold text-ink">{loading?'—':formatCents(subtotal)}</span></p>{error?<p className="mt-4 rounded-lg bg-sand p-3 text-sm font-semibold text-ink">{error}</p>:null}{validation?.warnings.length?<div className="mt-4 rounded-lg bg-sand p-3 text-sm font-semibold text-ink">{validation.warnings.map(w=><p key={w}>{w}</p>)}</div>:null}
   {hasBlockingIssue?<button disabled className="mt-6 min-h-14 w-full rounded-full bg-forest px-6 font-bold text-white opacity-50">Checkout unavailable</button>:<Link href="/checkout" className="mt-6 inline-flex min-h-14 w-full items-center justify-center rounded-full bg-forest px-6 font-bold text-white hover:bg-moss">Checkout</Link>}<Link href="/shop" className="mt-3 inline-flex min-h-11 w-full items-center justify-center font-semibold text-moss hover:text-forest">Continue Shopping</Link><p className="mt-4 text-center text-xs leading-5 text-ink/50">Prices and inventory are confirmed before payment. Secure payment is handled by Stripe.</p>
  </aside>
 </div>;
}
function Empty({signedIn}:{signedIn:boolean}){return <section className="mt-10 overflow-hidden rounded-[1.5rem] border border-ink/10 bg-white shadow-soft"><div className="grid gap-8 p-7 sm:p-10 lg:grid-cols-[1fr_22rem] lg:items-center"><div><h2 className="font-serif text-4xl font-bold text-ink">Your bag is empty.</h2><p className="mt-3 max-w-xl leading-7 text-ink/65">The Shutterbug shelf changes often. Browse tested cameras, printers, and one-of-a-kind finds when you are ready.</p><Link href="/shop" className="mt-6 inline-flex min-h-12 items-center rounded-full bg-forest px-7 font-bold text-white hover:bg-moss">Continue Shopping</Link></div><Image src="/shutterbug-checkout.png" alt="" width={500} height={375} className="aspect-[4/3] w-full rounded-lg bg-sand object-cover"/></div><div className="grid border-t border-ink/10 bg-[#faf4e8] sm:grid-cols-2 lg:grid-cols-4">{!signedIn?<EmptyLink href="/login?returnTo=%2Fbag" label="Sign In"/>:<EmptyLink href="/account" label="Account"/>}<EmptyLink href={signedIn?'/account/likes':'/login?returnTo=%2Faccount%2Flikes'} label="Saved Items"/><EmptyLink href="/categories/vintage-digital-cameras" label="Browse Cameras"/><EmptyLink href="/categories/printers" label="Browse Printers"/></div></section>}
function EmptyLink({href,label}:{href:string;label:string}){return <Link href={href} className="flex min-h-16 items-center justify-center border-b border-ink/10 px-4 font-semibold text-ink hover:bg-mint sm:border-r">{label}</Link>}