import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { TradeInOfferStatus } from '@/generated/prisma/client';
import { requireCustomer } from '@/lib/customer-auth';
import { formatCents } from '@/lib/money';
import { requirePrisma } from '@/lib/prisma';
import { statusTone, tradeInConditionLabels, tradeInStatusLabels } from '@/lib/trade-ins';
import { cancelTradeInDraft, respondToTradeInOffer } from '../actions';
export const metadata:Metadata={title:'Trade-In Details',robots:{index:false,follow:false}};
type Props={params:Promise<{id:string}>;searchParams?:Promise<{error?:string}>};
export default async function TradeInDetail({params,searchParams}:Props){
 const customer=await requireCustomer('/account/trade-ins');const {id}=await params;
 const item=await requirePrisma().tradeInSubmission.findFirst({where:{id,customerId:customer.id},include:{images:{orderBy:{sortOrder:'asc'}},offers:{orderBy:{createdAt:'desc'}},history:{orderBy:{createdAt:'desc'}}}});
 if(!item)notFound();const pending=item.offers.find(o=>o.status===TradeInOfferStatus.PENDING);const error=(await searchParams)?.error;
 return <section className="px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl">
  <Link href="/account/trade-ins" className="text-sm font-bold text-moss hover:underline">← My trade-ins</Link>
  <div className="mt-5 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-moss">{item.reference}</p><h1 className="mt-2 font-serif text-4xl font-bold text-ink">{item.brand||'Trade-in'} {item.modelUnknown?'Unknown model':item.model}</h1></div><span className={`rounded-full px-4 py-2 text-sm font-bold ${statusTone(item.status)}`}>{tradeInStatusLabels[item.status]}</span></div>
  {error?<p className="mt-5 rounded-lg bg-sand p-4 font-semibold text-ink">{error==='offer-expired'?'That offer has expired.':'That offer is no longer available.'}</p>:null}
  {pending?<section className="mt-7 rounded-[1.25rem] bg-forest p-6 text-white sm:p-8"><p className="text-sm font-bold uppercase tracking-[.18em] text-sand">{pending.kind==='REVISED'?'Revised final offer':'Preliminary offer'}</p><h2 className="mt-2 font-serif text-3xl font-bold">Choose the value that works for you</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-lg bg-white/10 p-5"><p className="text-sm text-white/70">Cash</p><p className="mt-1 font-serif text-4xl font-bold">{formatCents(pending.cashCents)}</p></div><div className="rounded-lg bg-white/10 p-5"><p className="text-sm text-white/70">Store credit</p><p className="mt-1 font-serif text-4xl font-bold">{formatCents(pending.storeCreditCents)}</p></div></div>{pending.note?<p className="mt-5 text-sm leading-6 text-white/80">{pending.note}</p>:null}{pending.expiresAt?<p className="mt-3 text-xs text-white/60">Offer expires {pending.expiresAt.toLocaleDateString('en-US')}.</p>:null}
   <div className="mt-6 flex flex-wrap gap-3"><form action={respondToTradeInOffer}><input type="hidden" name="tradeInId" value={item.id}/><input type="hidden" name="offerId" value={pending.id}/><input type="hidden" name="response" value="accept"/><button name="payout" value="CASH" className="min-h-11 rounded-full bg-white px-5 font-bold text-forest">Accept cash</button></form><form action={respondToTradeInOffer}><input type="hidden" name="tradeInId" value={item.id}/><input type="hidden" name="offerId" value={pending.id}/><input type="hidden" name="response" value="accept"/><button name="payout" value="STORE_CREDIT" className="min-h-11 rounded-full bg-sand px-5 font-bold text-ink">Accept store credit</button></form><form action={respondToTradeInOffer}><input type="hidden" name="tradeInId" value={item.id}/><input type="hidden" name="offerId" value={pending.id}/><input type="hidden" name="response" value="decline"/><button className="min-h-11 rounded-full border border-white/30 px-5 font-bold">Decline</button></form></div>
  </section>:null}
  <div className="mt-7 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-lg border border-ink/10 bg-white p-6"><h2 className="font-serif text-2xl font-bold text-ink">Submission details</h2><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><Info label="Type" value={item.itemType?.replaceAll('_',' ')||'Not set'}/><Info label="Condition" value={item.condition?tradeInConditionLabels[item.condition]:'Not set'}/><Info label="Quantity" value={String(item.quantity)}/><Info label="Powers on" value={item.powersOn===null?'Not tested':item.powersOn?'Yes':'No'}/><Info label="Payout preference" value={item.payoutPreference?.replaceAll('_',' ')||'Not set'}/><Info label="Included" value={item.includedItems.join(', ')||'None listed'}/></dl>{item.functionalNotes||item.cosmeticNotes||item.additionalNotes?<div className="mt-5 space-y-3 text-sm leading-6 text-ink/70">{item.functionalNotes?<p><strong>Function:</strong> {item.functionalNotes}</p>:null}{item.cosmeticNotes?<p><strong>Cosmetics:</strong> {item.cosmeticNotes}</p>:null}{item.additionalNotes?<p><strong>Notes:</strong> {item.additionalNotes}</p>:null}</div>:null}
   {item.status==='DRAFT'?<div className="mt-6 flex gap-3"><Link href={`/account/trade-ins/new?draft=${item.id}`} className="rounded-full bg-forest px-5 py-3 font-semibold text-white">Continue draft</Link><form action={cancelTradeInDraft}><input type="hidden" name="tradeInId" value={item.id}/><button className="rounded-full border border-ink/15 px-5 py-3 font-semibold text-ink">Cancel draft</button></form></div>:null}
  </section>
  <section className="rounded-lg border border-ink/10 bg-white p-6"><h2 className="font-serif text-2xl font-bold text-ink">Status history</h2><ol className="mt-5 space-y-4">{item.history.map(event=><li key={event.id} className="border-l-2 border-sage pl-4"><p className="font-semibold text-ink">{tradeInStatusLabels[event.status]}</p><p className="text-sm text-ink/65">{event.message}</p><time className="text-xs text-ink/50">{event.createdAt.toLocaleString('en-US')}</time></li>)}</ol>{item.shippingInstructions?<div className="mt-6 rounded-lg bg-mint p-4 text-sm leading-6 text-ink"><strong>Shipping or handoff instructions</strong><p className="mt-1">{item.shippingInstructions}</p></div>:null}</section></div>
  {item.images.length?<section className="mt-7"><h2 className="font-serif text-2xl font-bold text-ink">Private photos</h2><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">{item.images.map((image,index)=><Image key={image.id} src={`/api/trade-ins/images/${image.id}`} alt={`Trade-in photo ${index+1}`} width={500} height={375} unoptimized className="aspect-[4/3] w-full rounded-lg border border-ink/10 bg-cream object-cover"/>)}</div></section>:null}
 </div></section>
}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-bold uppercase tracking-[.12em] text-moss">{label}</dt><dd className="mt-1 capitalize text-ink">{value}</dd></div>}