ALTER TYPE "ProductCondition" ADD VALUE IF NOT EXISTS 'NEW';
ALTER TYPE "ProductCondition" ADD VALUE IF NOT EXISTS 'OPEN_BOX';
ALTER TYPE "ProductCondition" ADD VALUE IF NOT EXISTS 'VERY_GOOD';
ALTER TYPE "ProductCondition" ADD VALUE IF NOT EXISTS 'HEAVILY_USED';
ALTER TYPE "ProductCondition" ADD VALUE IF NOT EXISTS 'UNTESTED';
ALTER TYPE "ProductCondition" ADD VALUE IF NOT EXISTS 'REFURBISHED';

ALTER TABLE "Product"
  ADD COLUMN IF NOT EXISTS "manufacturer" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "subcategorySlug" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "productType" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "functionalStatus" TEXT NOT NULL DEFAULT 'Tested',
  ADD COLUMN IF NOT EXISTS "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "lensMount" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "filmFormat" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "storageType" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "includesMemoryCard" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "includesCase" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "includesStrap" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "includesManual" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "includesOriginalBox" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "samplePhotos" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "newArrival" BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS "Product_subcategorySlug_idx" ON "Product"("subcategorySlug");
CREATE INDEX IF NOT EXISTS "Product_productType_idx" ON "Product"("productType");
CREATE INDEX IF NOT EXISTS "Product_functionalStatus_idx" ON "Product"("functionalStatus");
CREATE INDEX IF NOT EXISTS "Product_newArrival_idx" ON "Product"("newArrival");
